package com.aicompany.core.model;

public enum PolicyKey {
    SEED_CAPITAL_USD,
    CHALLENGE_DAYS,
    CONTRADICTION_SEED_CAPITAL_MULTIPLE,
    SUCCESS_THRESHOLD_GOOD,
    SUCCESS_THRESHOLD_VERY_GOOD,
    SUCCESS_THRESHOLD_EXCELLENT,
    SUCCESS_THRESHOLD_EXTRAORDINARY
}
