http_port 3128
acl allowed dstdomain api.nuget.org pub.dev storage.googleapis.com
acl CONNECT method CONNECT
acl SSL_ports port 443
http_access deny CONNECT !SSL_ports
http_access allow allowed
http_access deny all
cache deny all
access_log stdio:/dev/stdout
cache_log stdio:/dev/stderr
pid_filename none
